import pandas as pd
match_event_info = pd.read_csv('df/df_event.csv')
match_round_info = pd.read_csv('df/df_round.csv')
match_home_score_info = pd.read_csv('df/df_home_team_score.csv')
odds_info = pd.read_csv('df/df_odds.csv')
period_info = pd.read_csv('df/df_statistics.csv')
match_votes_info = pd.read_csv('df/df_votes.csv')
match_venue_info = pd.read_csv('df/df_venue.csv')
match_away_score_info = pd.read_csv('df/df_away_team_score.csv')
power_info = pd.read_csv('df/df_power.csv')
match_tournament_info = pd.read_csv('df/df_tournament.csv')
match_home_team_info = pd.read_csv('df/df_home_team_1.csv')
match_time_info = pd.read_csv('df/df_time.csv')
match_season_info = pd.read_csv('df/df_season.csv')
match_away_team_info = pd.read_csv('df/df_away_team_1.csv')
game_info = pd.read_csv('df/df_pbp.csv')